config/routes.rb
Gemcutter::Application.routes.draw do
  ################################################################################
  # API v1

  namespace :api do
    namespace :v1 do
      resource :api_key, :only => :show do
        put :reset
      end
      resources :downloads, :only => :index do
        get :top, :on => :collection
      end
      constraints :id => Rubygem::ROUTE_PATTERN, :format => /json|xml|yaml/ do
        # In Rails 3.1, the following line can be replaced with:
        # resources :downloads, :only => :show, :format => true
        get 'downloads/:id.:format', :to => 'downloads#show', :as => 'download'
        # In Rails 3.1, the next TWO lines can be replaced with:
        # resources :versions, :only => :show, :format => true do
        get 'versions/:id.:format', :to => 'versions#show', :as => 'version'
        resources :versions, :only => :show do
          # In Rails 3.1, the next TWO lines can be replaced with:
          # resources :downloads, :only => :show, :controller => 'versions/downloads', :format => true do
          get 'downloads.:format', :to => 'versions/downloads#index', :as => 'downloads'
          resources :downloads, :only => :index, :controller => 'versions/downloads' do
            collection do
              # In Rails 3.1, the following line can be replaced with:
              # get :search, :format => true
              get 'search.:format', :to => 'versions/downloads#search', :as => 'search'
            end
          end
        end
      end

      resources :dependencies, :only => :index

      resources :rubygems, :path => 'gems', :only => [:create, :show, :index], :id => Rubygem::LAZY_ROUTE_PATTERN, :format => /json|xml|yaml/ do
        collection do
          delete :yank
          put :unyank
          get :latest
          get :just_updated
        end
        constraints :rubygem_id => Rubygem::ROUTE_PATTERN do
          resource :owners, :only => [:show, :create, :destroy]
        end
      end

      resource :search, :only => :show

      resources :web_hooks, :only => [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  ################################################################################
  # API v0

  scope :to => 'api/deprecated#index' do
    get 'api_key'
    put 'api_key/reset'

    post 'gems'
    get  'gems/:id.json'

    scope :path => 'gems/:rubygem_id' do
      put  'migrate'
      post 'migrate'
      get    'owners(.:format)'
      post   'owners(.:format)'
      delete 'owners(.:format)'
    end
  end

  ################################################################################
  # UI

  resource  :search,    :only => :show
  resource  :dashboard, :only => :show
  resources :profiles,  :only => :show
  resource  :profile,   :only => [:edit, :update]
  resources :stats,     :only => :index

  resources :rubygems, :only => :index, :path => 'gems' do
    constraints :rubygem_id => Rubygem::ROUTE_PATTERN do
      resource  :subscription, :only => [:create, :destroy]
      resources :versions,     :only => :index
      resource  :stats,        :only => :show
    end
  end

  constraints :id => Rubygem::ROUTE_PATTERN do
    resources :rubygems, :path => 'gems', :only => [:show, :edit, :update] do

      constraints :rubygem_id => Rubygem::ROUTE_PATTERN do
        resources :versions, :only => :show do
          resource :stats, :only => :show
        end
      end
    end
  end

  ################################################################################
  # Clearance Overrides

  resource :session, :only => [:new, :create]
  scope :path => 'users/:user_id' do
    resource :confirmation, :only => [:new, :create], :as => :user_confirmation
  end

  resources :passwords, :only => [:new, :create]

  resources :users do
    resource :password, :only => [:create, :edit, :update]
    resource :confirmation, :only => [:new, :create]
  end

  ################################################################################
  # Root

  root :to => 'home#index'

end

app/models/rubygem.rb
class Rubygem < ActiveRecord::Base
  SPECIAL_CHARACTERS = ".-_"
  ALLOWED_CHARACTERS = "[A-Za-z0-9#{Regexp.escape(SPECIAL_CHARACTERS)}]+"
  ROUTE_PATTERN      = /#{ALLOWED_CHARACTERS}/
  LAZY_ROUTE_PATTERN = /#{ALLOWED_CHARACTERS}?/
  NAME_PATTERN       = /\A#{ALLOWED_CHARACTERS}\Z/

  has_many :owners, :through => :ownerships, :source => :user
  has_many :ownerships, :dependent => :destroy
  has_many :subscribers, :through => :subscriptions, :source => :user
  has_many :subscriptions, :dependent => :destroy
  has_many :versions, :dependent => :destroy
  has_many :web_hooks, :dependent => :destroy
  has_one :linkset, :dependent => :destroy

  validate :ensure_name_format
  validates :name, :presence => true, :uniqueness => true

  def self.with_versions
    where("rubygems.id IN (SELECT rubygem_id FROM versions where versions.indexed IS true)")
  end

  def self.with_one_version
    select('rubygems.*').
    joins(:versions).
    group(column_names.map { |name| "rubygems.#{name}" }.join(', ')).
    having('COUNT(versions.id) = 1')
  end

  def self.name_is(name)
    where(:name => name.strip).limit(1)
  end

  def self.search(query)
    conditions = <<-SQL
      versions.indexed and
        (upper(name) like upper(:query) or
         upper(translate(name, '#{SPECIAL_CHARACTERS}', '#{' ' * SPECIAL_CHARACTERS.length}')) like upper(:query) or
         upper(versions.description) like upper(:query))
    SQL

    where(conditions, {:query => "%#{query.strip}%"}).
      includes(:versions).
      by_downloads
  end

  def self.name_starts_with(letter)
    where("upper(name) like upper(?)", "#{letter}%")
  end

  def self.total_count
    with_versions.count
  end

  def self.latest(limit=5)
    with_one_version.order("created_at desc").limit(limit)
  end

  def self.downloaded(limit=5)
    with_versions.by_downloads.limit(limit)
  end

  def self.letter(letter)
    name_starts_with(letter).order("name asc").with_versions
  end

  def self.letterize(letter)
    letter =~ /\A[A-Za-z]\z/ ? letter.upcase : 'A'
  end

  def self.monthly_dates
    (2..31).map { |n| n.days.ago.to_date }.reverse
  end

  def self.monthly_short_dates
    monthly_dates.map { |date| date.strftime("%m/%d") }
  end

  def self.versions_key(name)
    "r:#{name}"
  end

  def self.by_downloads
    order("rubygems.downloads desc")
  end

  def all_errors(version = nil)
    [self, linkset, version].compact.map do |ar|
      ar.errors.full_messages
    end.flatten.join(", ")
  end

  def public_versions(limit = nil)
    versions.published(limit).by_position
  end

  def hosted?
    versions.count.nonzero?
  end

  def unowned?
    ownerships.where(:approved => true).blank?
  end

  def owned_by?(user)
    ownerships.find_by_user_id(user.id).try(:approved) if user
  end

  def to_s
    versions.most_recent.try(:to_title) || name
  end

  def downloads
    Download.for(self)
  end

  def downloads_today
    versions.to_a.sum {|v| Download.today(v) }
  end

  def payload(version=versions.most_recent, host_with_port=HOST)
    {
      'name'              => name,
      'downloads'         => downloads,
      'version'           => version.number,
      'version_downloads' => version.downloads_count,
      'authors'           => version.authors,
      'info'              => version.info,
      'project_uri'       => "http://#{host_with_port}/gems/#{name}",
      'gem_uri'           => "http://#{host_with_port}/gems/#{version.full_name}.gem",
      'homepage_uri'      => linkset.try(:home),
      'wiki_uri'          => linkset.try(:wiki),
      'documentation_uri' => linkset.try(:docs),
      'mailing_list_uri'  => linkset.try(:mail),
      'source_code_uri'   => linkset.try(:code),
      'bug_tracker_uri'   => linkset.try(:bugs),
      'dependencies'      => {
        'development' => version.dependencies.development.to_a,
        'runtime'     => version.dependencies.runtime.to_a
      }
    }
  end

  def as_json(options={})
    payload
  end

  def to_xml(options={})
    payload.to_xml(options.merge(:root => 'rubygem'))
  end

  def to_param
    name
  end

  def with_downloads
    "#{name} (#{downloads})"
  end

  def pushable?
    new_record? || versions.indexed.count.zero?
  end

  def create_ownership(user)
    if unowned? && !user.try(:rubyforge_importer?)
      ownerships.create(:user => user, :approved => true)
    end
  end

  def update_versions!(version, spec)
    version.update_attributes_from_gem_specification!(spec)
  end

  def update_dependencies!(version, spec)
    spec.dependencies.each do |dependency|
      version.dependencies.create!(:gem_dependency => dependency)
    end
  rescue ActiveRecord::RecordInvalid => ex
    # ActiveRecord can't chain a nested error here, so we have to add and reraise
    errors[:base] << ex.message
    raise ex
  end

  def update_linkset!(spec)
    self.linkset ||= Linkset.new
    self.linkset.update_attributes_from_gem_specification!(spec)
    self.linkset.save!
  end

  def update_attributes_from_gem_specification!(version, spec)
    Rubygem.transaction do
      save!
      update_versions!     version, spec
      update_dependencies! version, spec
      update_linkset!      spec
    end
  end

  def reorder_versions
    numbers = self.reload.versions.sort.reverse.map(&:number).uniq

    self.versions.each do |version|
      Version.update_all({:position => numbers.index(version.number)}, {:id => version.id})
    end

    self.versions.update_all(:latest => false)

    self.versions.release.indexed.inject(Hash.new{|h, k| h[k] = []}) do |platforms, version|
      platforms[version.platform] << version
      platforms
    end.each_value do |platforms|
      Version.update_all({:latest => true}, {:id => platforms.sort.last.id})
    end
  end

  def yank!(version)
    version.yank!
    if versions.indexed.count.zero?
      ownerships.each(&:delete)
    end
  end

  def find_or_initialize_version_from_spec(spec)
    version = self.versions.find_or_initialize_by_number_and_platform(spec.version.to_s, spec.original_platform.to_s)
    version.rubygem = self
    version
  end

  def monthly_downloads
    key_dates = self.class.monthly_dates.map(&:to_s)
    $redis.hmget(Download.history_key(self), *key_dates).map(&:to_i)
  end

  def first_built_date
    versions.by_built_at.limit(1).last.built_at
  end

  private

  def ensure_name_format
    if name.class != String
      errors.add :name, "must be a String"
    elsif name =~ /\A[\d]+\Z/
      errors.add :name, "must include at least one letter"
    elsif name !~ NAME_PATTERN
      errors.add :name, "can only include letters, numbers, dashes, and underscores"
    end
  end
end

app/controllers/api/v1/rubygems_controller.rb
class Api::V1::RubygemsController < Api::BaseController
  skip_before_filter :verify_authenticity_token, :only => [:create, :yank, :unyank]

  before_filter :authenticate_with_api_key, :only => [:index, :create, :yank, :unyank]
  before_filter :verify_authenticated_user, :only => [:index, :create, :yank, :unyank]
  before_filter :find_gem,                  :only => [:show]
  before_filter :find_gem_by_name,          :only => [:yank, :unyank]
  before_filter :validate_gem_and_version,  :only => [:yank, :unyank]

  respond_to :json, :xml, :yaml, :on => [:index, :show, :latest, :just_updated]

  def index
    @rubygems = current_user.rubygems.with_versions
    respond_with(@rubygems, :yamlish => true)
  end

  def show
    if @rubygem.hosted?
      respond_with(@rubygem, :yamlish => true)
    else
      render :text => "This gem does not exist.", :status => :not_found
    end
  end

  def create
    gemcutter = Pusher.new(current_user, request.body, request.host_with_port)
    gemcutter.process
    render :text => gemcutter.message, :status => gemcutter.code
  end

  def yank
    if @version.indexed?
      @rubygem.yank!(@version)
      render :text => "Successfully yanked gem: #{@version.to_title}"
    else
      render :text => "The version #{params[:version]} has already been yanked.", :status => :unprocessable_entity
    end
  end

  def unyank
    if !@version.indexed?
      @version.unyank!
      render :text => "Successfully unyanked gem: #{@version.to_title}"
    else
      render :text => "The version #{params[:version]} is already indexed.", :status => :unprocessable_entity
    end
  end

  def latest
    @rubygems = Rubygem.latest(50)
    respond_with(@rubygems, :yamlish => true)
  end

  def just_updated
    @versions = Version.just_updated(50)
    respond_with(@versions, :yamlish => true)
  end

  private

  def validate_gem_and_version
    if !@rubygem.hosted?
      render :text => "This gem does not exist.", :status => :not_found
    elsif !@rubygem.owned_by?(current_user)
      render :text => "You do not have permission to yank this gem.", :status => :forbidden
    else
      begin
        slug = params[:platform].blank? ? params[:version] : "#{params[:version]}-#{params[:platform]}"
        @version = Version.find_from_slug!(@rubygem, slug)
      rescue ActiveRecord::RecordNotFound
        render :text => "The version #{params[:version]} does not exist.", :status => :not_found
      end
    end
  end
end

app/controllers/rubygems_controller.rb
class RubygemsController < ApplicationController
  before_filter :redirect_to_root, :only => [:edit, :update], :unless => :signed_in?
  before_filter :find_gem, :only => [:edit, :update, :show]
  before_filter :load_gem, :only => [:edit, :update]

  def index
    respond_to do |format|
      format.html do
        @letter = Rubygem.letterize(params[:letter])
        @gems   = Rubygem.letter(@letter).paginate(:page => params[:page])
      end
      format.atom do
        @versions = Version.published(20)
        render 'versions/feed'
      end
    end
  end

  def show
    @latest_version = @rubygem.versions.most_recent
    @versions       = @rubygem.public_versions(5)
  end

  def edit
  end

  def update
    if @linkset.update_attributes(params[:linkset])
      redirect_to rubygem_path(@rubygem)
      flash[:success] = "Gem links updated."
    else
      render :edit
    end
  end

  protected
    def load_gem
      if !@rubygem.owned_by?(current_user)
        flash[:warning] = "You do not have permission to edit this gem."
        redirect_to root_url
      end

      @linkset = @rubygem.linkset
    end
end

app/helpers/rubygems_helper.rb
module RubygemsHelper
  def link_to_page(text, url)
    link_to(text, url, :rel => 'nofollow') if url.present?
  end

  def link_to_directory
    ("A".."Z").map { |letter| link_to(letter, rubygems_path(:letter => letter)) }.join
  end

  def simple_markup(text)
    if text =~ /^==+ [A-Z]/
      RDoc::Markup.new.convert(text, RDoc::Markup::ToHtml.new).html_safe
    else
      content_tag :p, text
    end
  end

  def subscribe_link(rubygem)
    if signed_in?
      subscribe = link_to 'Subscribe', rubygem_subscription_path(rubygem),
        :remote => true,
        :method => :post,
        :id     => 'subscribe',
        :class  => 'toggler',
        :style  => rubygem.subscribers.find_by_id(current_user.try(:id)) ? 'display:none' : 'display:inline-block'
    else
      link_to 'Subscribe', sign_in_path, :id => :subscribe, :class => :toggler
    end
  end

  def unsubscribe_link(rubygem)
    if signed_in?
      link_to 'Unsubscribe', rubygem_subscription_path(rubygem),
        :remote  => true,
        :method  => :delete,
        :id    => 'unsubscribe',
        :class => :toggler,
        :style => rubygem.subscribers.find_by_id(current_user.try(:id)) ? 'display:inline-block' : 'display:none'
    end
  end

  def download_link(version)
    link_to "Download", "/downloads/#{version.full_name}.gem", :id => :download
  end

  def documentation_link(version, linkset)
    link_to 'Documentation', documentation_path(version), :id => :docs if linkset.nil? ||
      linkset.docs.blank?
  end

  def documentation_path(version)
    "http://rubydoc.info/gems/#{version.rubygem.name}/#{version.number}/frames"
  end

  def stats_options(rubygem)
    [
      ['Overview', rubygem_stats_path(rubygem)],
      *rubygem.versions.sort.reverse.map do |version|
        [version.slug, rubygem_version_stats_path(rubygem, version.slug)]
      end
    ]
  end

  def links_to_owners(rubygem)
    rubygem.owners.sort_by(&:id).map do |owner|
      link_to gravatar(48, "gravatar-#{owner.id}", owner), profile_path(owner.display_id),
        :alt => owner.display_handle, :title => owner.display_handle
    end.join.html_safe
  end

  def nice_date_for(time)
    time.to_date.to_formatted_s(:long)
  end
end

app/views/rubygems/_clippy.html.erb
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
        width="110"
        id="<%= embed %>" >
  <param name="movie" value="/<%= embed %>.swf"/>
  <param name="allowScriptAccess" value="always" />
  <param name="quality" value="high" />
  <param name="scale" value="noscale" />
  <param NAME="FlashVars" value="text=<%= text %>">
  <param name="wmode" value="transparent">
  <embed src="/<%= embed %>.swf"
         width="110"
         name="clippy"
         quality="high"
         allowScriptAccess="always"
         type="application/x-shockwave-flash"
         pluginspage="http://www.macromedia.com/go/getflashplayer"
         FlashVars="text=<%= text %>"
         wmode="transparent"
  />
</object>

app/views/rubygems/_dependencies.html.erb
<% if dependencies.present? && @latest_version.indexed %>
  <div class="dependencies" id="<%= dependencies.first.scope %>_dependencies">
    <h5><%= t '.header', :title => dependencies.first.scope.titleize %></h5>
    <ol>
    <% dependencies.each do |dependency| %>
      <li>
        <a href="<%= rubygem_url(dependency.rubygem) %>">
          <strong><%= dependency.rubygem.name %></strong> <%= dependency.clean_requirements %>
        </a>
      </li>
    <% end %>
    </ol>
  </div>
<% end %>

app/views/rubygems/_rubygem.html.erb
<li>
  <%= download_count rubygem %>
  <a href="<%= rubygem_path(rubygem) %>">
    <strong><%= rubygem %></strong>
    <%= short_info(rubygem.versions.most_recent) %>
  </a>
</li>

app/views/rubygems/edit.html.erb
<% @title = t('.title') %>
<% @subtitle = t('.subtitle', :gem => @rubygem.name) %>
<p><%= t '.other_fields_notice' %></p>
<%= error_messages_for :linkset, :object_name => "gem" %>
<%= form_for @rubygem.linkset, :url => rubygem_url(@rubygem), :method => :put do |form| %>
  <div class="url_field">
    <%= form.label :code %>
    <%= form.text_field :code, :size => 25 %>
  </div>
  <div class="url_field">
    <%= form.label :docs %>
    <%= form.text_field :docs, :size => 25 %>
  </div>
  <div class="url_field">
    <%= form.label :wiki %>
    <%= form.text_field :wiki, :size => 25 %>
  </div>
  <div class="url_field">
    <%= form.label :mail %>
    <%= form.text_field :mail, :size => 25 %>
  </div>
  <div class="url_field">
    <%= form.label :bugs %>
    <%= form.text_field :bugs, :size => 25 %>
  </div>
    <%= form.submit t('update'), :disable_with => t('form_disable_with') %>
<% end %>

app/views/rubygems/index.html.erb
<% @title = t('.title') %>
<% @subtitle = t('.subtitle', :prefix => content_tag(:em, @letter)).html_safe %>
<div class="directory border">
  <ol>
    <% ("A".."Z").each do |letter| %><li><%= link_to(letter, rubygems_path(:letter => letter)) %></li><% end %>
  </ol>
</div>
<p class="entries">
  <%= page_entries_info @gems, :entry_name => 'gem' %>
</p>
<div class="gems border">
  <ol>
    <%= render @gems %>
  </ol>
</div>
<%= will_paginate @gems %>

app/views/rubygems/show.html.erb
<% @title = @rubygem.name %>
<% @subtitle = @latest_version.try(:slug) %>

<% if @rubygem.versions.count.zero? %>
  <p><%= t '.not_hosted_notice' %></p>
<% else %>
  <% if @latest_version.indexed %>
    <div id="markup">
      <%= simple_markup(@latest_version.info) %>
    </div>

    <div class="border">
      <%= render :partial => "rubygems/clippy", :locals => { :embed => "clippy", :text => @latest_version.to_install } %>
      <div class="install">
        <div class="instructions"><strong><%= t '.install' %></strong><span><%= @latest_version.to_install %></span></div>
      </div>
    </div>
  <% else %>
    <p><%= t('.yanked_notice', :more_info_link => link_to(t('.yank_info_link_text'), "http://help.rubygems.org/faqs/gemcutter/removing-a-published-rubygem")).html_safe %></p>
  <% end %>

  <div class="border">
    <div class="meta">
      <div class="admin">
        <%= link_to t('edit'), edit_rubygem_path(@rubygem), :id => "edit" if @rubygem.owned_by?(current_user) %>
        <%= download_link(@latest_version) %>
        <%= documentation_link(@latest_version, @rubygem.linkset) %>
        <% if @latest_version.indexed %>
          <%= subscribe_link(@rubygem) %>
          <%= unsubscribe_link(@rubygem) %>
          <%= link_to t('.stats_header'), rubygem_stats_path(@rubygem), :id => "stats" %>
        <% end %>
      </div>

      <% if @latest_version.indexed %>
        <div class="who">
          <div class="authors">
            <% if @latest_version.authors.present? %>
              <h5><%= t '.authors_header' %></h5>
              <p><%= @latest_version.authors %></p>
            <% end %>
          </div>

          <div class="downloads counter" data-href="<%= api_v1_download_path(@latest_version.full_name, :format => 'json') %>">
            <span>
              <%= t('stats.show.total_downloads', :count => content_tag(:strong, number_with_delimiter(@rubygem.downloads))).html_safe %>
            </span>
            <span>
              <%= t('.downloads_for_this_version', :count => content_tag(:strong, number_with_delimiter(@latest_version.downloads_count))).html_safe %>
            </span>
          </div>

          <% if @rubygem.owners.present? %>
            <div class="owners">
              <h5><%= t '.owners_header' %></h5>
              <p><%= links_to_owners(@rubygem) %></p>
            </div>
          <% end %>

        </div>

        <% if @rubygem.linkset.present? %>
          <div class="links">
            <h5><%= t '.links.header' %></h5>
            <%= link_to_page t('.links.home'), @rubygem.linkset.home %>
            <%= link_to_page t('.links.code'), @rubygem.linkset.code %>
            <%= link_to_page t('.links.docs'), @rubygem.linkset.docs %>
            <%= link_to_page t('.links.wiki'), @rubygem.linkset.wiki %>
            <%= link_to_page t('.links.mail'), @rubygem.linkset.mail %>
            <%= link_to_page t('.links.bugs'), @rubygem.linkset.bugs %>
          </div>
        <% end %>

        <div class="bundler">
          <h5><%= t '.bundler_header' %></h5>
          <%= render :partial => "rubygems/clippy", :locals => { :embed => "github_clippy", :text => @latest_version.to_bundler } %>
          <pre><code><%= @latest_version.to_bundler %></code></pre>
        </div>
      <% end %>

    <% if @versions.present? %>
      <div class="versions">
        <h5><%= t '.versions_header' %></h5>
        <ol>
          <%= render @versions %>
        </ol>
        <% if @rubygem.versions.count > 5 %>
          <%= link_to t('.show_all_versions', :count => @rubygem.versions.count), rubygem_versions_url(@rubygem), :class => "more" %>
        <% end %>
      </div>
    <% end %>

      <%= render :partial => "rubygems/dependencies", :locals => { :dependencies => @latest_version.dependencies.runtime } %>
      <%= render :partial => "rubygems/dependencies", :locals => { :dependencies => @latest_version.dependencies.development } %>
    </div>
  </div>
<% end %>