config/routes.rb
Gemcutter::Application.routes.draw do
  ################################################################################
  # API v1

  namespace :api do
    namespace :v1 do
      resource :api_key, :only => :show do
        put :reset
      end
      resources :downloads, :only => :index do
        get :top, :on => :collection
      end
      constraints :id => Rubygem::ROUTE_PATTERN, :format => /json|xml|yaml/ do
        # In Rails 3.1, the following line can be replaced with:
        # resources :downloads, :only => :show, :format => true
        get 'downloads/:id.:format', :to => 'downloads#show', :as => 'download'
        # In Rails 3.1, the next TWO lines can be replaced with:
        # resources :versions, :only => :show, :format => true do
        get 'versions/:id.:format', :to => 'versions#show', :as => 'version'
        resources :versions, :only => :show do
          # In Rails 3.1, the next TWO lines can be replaced with:
          # resources :downloads, :only => :show, :controller => 'versions/downloads', :format => true do
          get 'downloads.:format', :to => 'versions/downloads#index', :as => 'downloads'
          resources :downloads, :only => :index, :controller => 'versions/downloads' do
            collection do
              # In Rails 3.1, the following line can be replaced with:
              # get :search, :format => true
              get 'search.:format', :to => 'versions/downloads#search', :as => 'search'
            end
          end
        end
      end

      resources :dependencies, :only => :index

      resources :rubygems, :path => 'gems', :only => [:create, :show, :index], :id => Rubygem::LAZY_ROUTE_PATTERN, :format => /json|xml|yaml/ do
        collection do
          delete :yank
          put :unyank
          get :latest
          get :just_updated
        end
        constraints :rubygem_id => Rubygem::ROUTE_PATTERN do
          resource :owners, :only => [:show, :create, :destroy]
        end
      end

      resource :search, :only => :show

      resources :web_hooks, :only => [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  ################################################################################
  # API v0

  scope :to => 'api/deprecated#index' do
    get 'api_key'
    put 'api_key/reset'

    post 'gems'
    get  'gems/:id.json'

    scope :path => 'gems/:rubygem_id' do
      put  'migrate'
      post 'migrate'
      get    'owners(.:format)'
      post   'owners(.:format)'
      delete 'owners(.:format)'
    end
  end

  ################################################################################
  # UI

  resource  :search,    :only => :show
  resource  :dashboard, :only => :show
  resources :profiles,  :only => :show
  resource  :profile,   :only => [:edit, :update]
  resources :stats,     :only => :index

  resources :rubygems, :only => :index, :path => 'gems' do
    constraints :rubygem_id => Rubygem::ROUTE_PATTERN do
      resource  :subscription, :only => [:create, :destroy]
      resources :versions,     :only => :index
      resource  :stats,        :only => :show
    end
  end

  constraints :id => Rubygem::ROUTE_PATTERN do
    resources :rubygems, :path => 'gems', :only => [:show, :edit, :update] do

      constraints :rubygem_id => Rubygem::ROUTE_PATTERN do
        resources :versions, :only => :show do
          resource :stats, :only => :show
        end
      end
    end
  end

  ################################################################################
  # Clearance Overrides

  resource :session, :only => [:new, :create]
  scope :path => 'users/:user_id' do
    resource :confirmation, :only => [:new, :create], :as => :user_confirmation
  end

  resources :passwords, :only => [:new, :create]

  resources :users do
    resource :password, :only => [:create, :edit, :update]
    resource :confirmation, :only => [:new, :create]
  end

  ################################################################################
  # Root

  root :to => 'home#index'

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_filter :authenticate_with_api_key, :if => lambda { |controller| controller.request.format.atom? }
  before_filter :redirect_to_root, :unless => :signed_in?

  def show
    respond_to do |format|
      format.html do
        @my_gems = current_user.rubygems.with_versions
        @latest_updates = Version.subscribed_to_by(current_user).published(20)
        @subscribed_gems = current_user.subscribed_gems.with_versions
      end
      format.atom do
        @versions = Version.subscribed_to_by(current_user).published(20)
        render 'versions/feed'
      end
    end
  end

end

app/views/dashboards/show.html.erb
<div class="subscribed">
  <h3><%= t '.latest' %></h3><%= link_to image_tag("feed.png"), dashboard_url(:api_key => current_user.api_key, :format => :atom), :id => "feed", :title => t('.latest_title') %>
  <div class="gems">
    <% if @latest_updates.empty? %>
      <p><%= t('.no_subscriptions', :gem_link => link_to(t('.gem_link_text'), rubygem_path("gemcutter"))).html_safe %>
      </p>
    <% else %>
      <ol>
        <% @latest_updates.each do |version| %>
        <li>
          <a href="<%= rubygem_url(version.rubygem) %>">
            <div class="top">
              <strong>
                <%= version.to_title %>
              </strong>
              <%= t 'time_ago', :duration => time_ago_in_words(version.created_at) %>
            </div>
            <%= short_info(version) %>
          </a>
        </li>
        <% end %>
      </ol>
    <% end %>
  </div>
</div>

<div class="mine">
  <h3><%= t '.mine' %></h3>
  <div class="gems">
    <% if @my_gems.empty? %>
      <p>
        <%= t('.no_owned', :creating_link => link_to(t('.creating_link_text'), page_url("create")),
                           :migrating_link => link_to(t('.migrating_link_text'), page_url("migrate"))).html_safe %>
      </p>
    <% else %>
      <ol>
      <% @my_gems.each do |rubygem| %>
        <li>
          <%= download_count(rubygem) %>
          <%= link_to rubygem.name, rubygem, :title => short_info(rubygem.versions.most_recent) %>
        </li>
      <% end %>
      </ol>
    <% end %>
  </div>

  <% if @subscribed_gems.present? %>
    <h3><%= t '.my_subscriptions' %></h3>
    <div class="gems">
      <ol>
      <% current_user.subscribed_gems.each do |gem| %>
        <li>
          <%= download_count(gem) %>
          <%= link_to gem, gem, :title => short_info(gem.versions.most_recent) %>
        </li>
      <% end %>
      </ol>
    </div>
  <% end %>
</div>

<div class="clear">
</div>